# Generated by Django 5.1.15 on 2026-06-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Колдонуучу'), ('assistant', 'AI мугалим')], max_length=16, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Мазмуну')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Убакыт')),
            ],
            options={
                'verbose_name': 'Чат билдирүүсү',
                'verbose_name_plural': 'Чат билдирүүлөрү',
                'ordering': ['created_at'],
            },
        ),
    ]
