# Generated by Django 5.1.15 on 2026-06-15 04:04

import core_educational.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган убакыт')),
                ('name_kg', models.CharField(max_length=120, verbose_name='Аты (кыргызча)')),
                ('name_ru', models.CharField(max_length=120, verbose_name='Аты (орусча)')),
                ('slug', models.SlugField(help_text='URL үчүн уникалдуу идентификатор (мисалы: matematika).', max_length=140, unique=True, verbose_name='Slug')),
                ('icon_name', models.CharField(help_text='Фронтенд иконка компонентинин аты (мисалы: calculator).', max_length=64, verbose_name='Иконка аты')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активдүү')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Тизмеде көрсөтүү ирети.', verbose_name='Иреттөө')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметтер',
                'ordering': ['sort_order', 'name_kg'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='core_educat_is_acti_4d6ac5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган убакыт')),
                ('title', models.CharField(max_length=255, verbose_name='Аталышы')),
                ('content_text', models.TextField(help_text='Теманын негизги тексттик мазмуну.', verbose_name='Мазмуну')),
                ('video_url', models.URLField(blank=True, help_text='YouTube же башка видео платформанын шилтемesi.', validators=[django.core.validators.URLValidator()], verbose_name='Видео шилтемesi')),
                ('pdf_file', models.FileField(blank=True, help_text='Кошумча окуу материалы (PDF).', null=True, upload_to=core_educational.models.topic_pdf_upload_path, verbose_name='PDF файл')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Иреттөө')),
                ('section_title', models.CharField(default='Негизги бөлүм', help_text='Темаларды топтоо үчүн бөлүм аталышы.', max_length=120, verbose_name='Бөлүм')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Жарыяланган')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core_educational.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темалар',
                'ordering': ['subject', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган убакыт')),
                ('question_text', models.TextField(verbose_name='Суроо')),
                ('options', models.JSONField(default=list, help_text='JSON массив: [{"key": "a", "text": "..."}, ...]', verbose_name='Жооп варианттары')),
                ('correct_answer', models.CharField(help_text='options ичиндеги key мааниси.', max_length=32, verbose_name='Туура жооп')),
                ('points', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Упай')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Иреттөө')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активдүү')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core_educational.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тест суроосу',
                'verbose_name_plural': 'Тест суроолору',
                'ordering': ['topic', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Аякталды')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Бул тема боюнча топтолгон упай.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Упай')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган убакыт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL, verbose_name='Колдонуучу')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core_educational.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Прогресс',
                'verbose_name_plural': 'Прогресстер',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'is_published', 'sort_order'], name='core_educat_subject_1776bd_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['topic', 'is_active', 'sort_order'], name='core_educat_topic_i_d99404_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'is_completed'], name='core_educat_user_id_e63c21_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['topic', 'is_completed'], name='core_educat_topic_i_d5beeb_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['-updated_at'], name='core_educat_updated_da5a93_idx'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='core_educational_progress_user_topic_unique'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='core_educational_progress_score_non_negative'),
        ),
    ]
